<a href="https://colab.research.google.com/github/unerret/myproject/blob/main/assignment_on_two_sample_ttest_%2Ccorrelation_and_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install scipy

Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (1.13.1)
Requirement already satisfied: numpy<2.3,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from scipy) (1.26.4)

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
df = pd.read_csv('/content/drive/My Drive/rideshare_2022_cleaned.csv')
clean =df.dropna()
clean.head(15)

,trip_start_timestamp,trip_seconds,trip_miles,fare,tip,additional_charges,trip_total,shared_trip_authorized,trips_pooled,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,date,weekday
2,2022-01-01 00:00:00,275.0,1.5,7.5,0.0,1.02,8.52,0,1,41.792357,-87.617931,41.812949,-87.617860,2022-01-01,Saturday
3,2022-01-01 00:00:00,243.0,1.0,5.0,0.0,2.36,7.36,0,1,41.936310,-87.651563,41.943155,-87.640698,2022-01-01,Saturday
4,2022-01-01 00:00:00,364.0,1.3,5.0,0.0,2.36,7.36,0,1,41.921855,-87.646211,41.936237,-87.656412,2022-01-01,Saturday
5,2022-01-01 00:00:00,467.0,2.2,7.5,0.0,2.41,9.91,0,1,41.928763,-87.665677,41.899737,-87.664954,2022-01-01,Saturday
6,2022-01-01 00:00:00,903.0,4.1,12.5,0.0,2.89,15.39,0,1,41.944227,-87.655998,41.899602,-87.633308,2022-01-01,Saturday
7,2022-01-01 00:00:00,142.0,0.6,7.5,0.0,2.87,10.37,0,1,41.874005,-87.663518,41.874005,-87.663518,2022-01-01,Saturday
8,2022-01-01 00:00:00,315.0,1.2,7.5,0.0,2.87,10.37,0,1,41.880994,-87.632746,41.885281,-87.657233,2022-01-01,Saturday
9,2022-01-01 00:00:00,1201.0,9.8,17.5,0.0,1.02,18.52,0,1,41.878866,-87.625192,41.922761,-87.699155,2022-01-01,Saturday
10,2022-01-01 00:00:00,714.0,2.8,7.5,6.0,2.77,16.27,0,1,41.809018,-87.659167,41.817366,-87.698861,2022-01-01,Saturday
11,2022-01-01 00:00:00,964.0,1.5,10.0,5.0,2.87,17.87,0,1,41.885281,-87.657233,41.884987,-87.620993,2022-01-01,Saturday
12,2022-01-01 00:00:00,1425.0,1.3,27.5,5.0,0.00,32.50,0,1,41.892042,-87.631864,41.891972,-87.612945,2022-01-01,Saturday
13,2022-01-01 00:00:00,846.0,4.4,10.0,0.0,3.22,13.22,0,1,41.907492,-87.635760,41.950673,-87.666536,2022-01-01,Saturday
14,2022-01-01 00:00:00,1120.0,10.2,20.0,0.0,1.02,21.02,0,1,41.901207,-87.676356,41.985015,-87.804532,2022-01-01,Saturday
15,2022-01-01 00:15:00,526.0,2.4,7.5,0.0,2.48,9.98,0,1,41.929047,-87.651311,41.901567,-87.638404,2022-01-01,Saturday
16,2022-01-01 00:15:00,711.0,4.6,10.0,5.0,3.60,18.60,0,1,41.877406,-87.621972,41.908379,-87.670945,2022-01-01,Saturday

In [ ]:
ac = clean['additional_charges'].head(15)
tt = clean['trip_total'].head(15)
print(ac)
print(tt)

2     1.02
3     2.36
4     2.36
5     2.41
6     2.89
7     2.87
8     2.87
9     1.02
10    2.77
11    2.87
12    0.00
13    3.22
14    1.02
15    2.48
16    3.60
Name: additional_charges, dtype: float64
2      8.52
3      7.36
4      7.36
5      9.91
6     15.39
7     10.37
8     10.37
9     18.52
10    16.27
11    17.87
12    32.50
13    13.22
14    21.02
15     9.98
16    18.60
Name: trip_total, dtype: float64

In [ ]:
nac = np.array(ac)
ntt = np.array(tt)

t_test, p_value = stats.ttest_ind(nac, ntt,equal_var=True)
t_test2, p_value2 = stats.ttest_ind(nac, ntt)
print(t_test, p_value)

-6.985564786246314 1.349883472904192e-07

In [ ]:
df = 28
alpha = 0.05
t_critical = stats.t.ppf(1-alpha/2,df)
print(t_critical)

2.048407141795244

In [ ]:
if(t_critical < abs(t_test)):
  print("Reject null hypothesis")
else:
  print("Accept null hypothesis")

Reject null hypothesis

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
df = pd.read_csv('/content/drive/My Drive/rideshare_2022_cleaned.csv')
clean =df.dropna()
clean.head(15)

,trip_start_timestamp,trip_seconds,trip_miles,fare,tip,additional_charges,trip_total,shared_trip_authorized,trips_pooled,pickup_centroid_latitude,pickup_centroid_longitude,dropoff_centroid_latitude,dropoff_centroid_longitude,date,weekday
2,2022-01-01 00:00:00,275.0,1.5,7.5,0.0,1.02,8.52,0,1,41.792357,-87.617931,41.812949,-87.617860,2022-01-01,Saturday
3,2022-01-01 00:00:00,243.0,1.0,5.0,0.0,2.36,7.36,0,1,41.936310,-87.651563,41.943155,-87.640698,2022-01-01,Saturday
4,2022-01-01 00:00:00,364.0,1.3,5.0,0.0,2.36,7.36,0,1,41.921855,-87.646211,41.936237,-87.656412,2022-01-01,Saturday
5,2022-01-01 00:00:00,467.0,2.2,7.5,0.0,2.41,9.91,0,1,41.928763,-87.665677,41.899737,-87.664954,2022-01-01,Saturday
6,2022-01-01 00:00:00,903.0,4.1,12.5,0.0,2.89,15.39,0,1,41.944227,-87.655998,41.899602,-87.633308,2022-01-01,Saturday
7,2022-01-01 00:00:00,142.0,0.6,7.5,0.0,2.87,10.37,0,1,41.874005,-87.663518,41.874005,-87.663518,2022-01-01,Saturday
8,2022-01-01 00:00:00,315.0,1.2,7.5,0.0,2.87,10.37,0,1,41.880994,-87.632746,41.885281,-87.657233,2022-01-01,Saturday
9,2022-01-01 00:00:00,1201.0,9.8,17.5,0.0,1.02,18.52,0,1,41.878866,-87.625192,41.922761,-87.699155,2022-01-01,Saturday
10,2022-01-01 00:00:00,714.0,2.8,7.5,6.0,2.77,16.27,0,1,41.809018,-87.659167,41.817366,-87.698861,2022-01-01,Saturday
11,2022-01-01 00:00:00,964.0,1.5,10.0,5.0,2.87,17.87,0,1,41.885281,-87.657233,41.884987,-87.620993,2022-01-01,Saturday
12,2022-01-01 00:00:00,1425.0,1.3,27.5,5.0,0.00,32.50,0,1,41.892042,-87.631864,41.891972,-87.612945,2022-01-01,Saturday
13,2022-01-01 00:00:00,846.0,4.4,10.0,0.0,3.22,13.22,0,1,41.907492,-87.635760,41.950673,-87.666536,2022-01-01,Saturday
14,2022-01-01 00:00:00,1120.0,10.2,20.0,0.0,1.02,21.02,0,1,41.901207,-87.676356,41.985015,-87.804532,2022-01-01,Saturday
15,2022-01-01 00:15:00,526.0,2.4,7.5,0.0,2.48,9.98,0,1,41.929047,-87.651311,41.901567,-87.638404,2022-01-01,Saturday
16,2022-01-01 00:15:00,711.0,4.6,10.0,5.0,3.60,18.60,0,1,41.877406,-87.621972,41.908379,-87.670945,2022-01-01,Saturday

In [ ]:
x = clean[['additional_charges']]
y = clean['trip_total']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(460388, 1)
(115097, 1)
(460388,)
(115097,)

In [ ]:
x = clean[['additional_charges']]
y = clean['trip_total']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)
print(f"the dataset for training is {xtrain}")
print(f"the dataset for testing is {xtest}")
print(f"the target for training is {ytrain}")
print(f"the target for testing is {ytest}")

the dataset for training is         additional_charges
172510                3.74
50462                 2.82
10848                 1.02
659570                3.14
530380               10.80
...                    ...
130317                2.91
309129                1.28
437408                3.81
156096                1.24
144196                3.53

[460388 rows x 1 columns]
the dataset for testing is         additional_charges
657510                3.54
90029                 2.36
373608                1.28
332985                2.37
458875                3.26
...                    ...
540565                4.91
170586                2.91
620978                1.32
196694               18.35
313831                0.00

[115097 rows x 1 columns]
the target for training is 172510    16.24
50462     20.32
10848     19.02
659570    10.64
530380    38.80
          ...
130317    10.41
309129    13.78
437408    26.31
156096    10.74
144196    18.53
Name: trip_total, Length: 460388, dtype: float64
the target for testing is 657510    13.54
90029      9.86
373608    16.28
332985     9.87
458875    15.76
          ...
540565    19.91
170586    27.91
620978    13.82
196694    75.35
313831    37.50
Name: trip_total, Length: 115097, dtype: float64

In [ ]:
model = LinearRegression().fit(xtrain,ytrain)

In [ ]:
ypredict = model.predict(xtrain)
print (f"the predicted values are {ypredict}")

the predicted values are [20.96037554 18.78141268 14.51822449 ... 21.12616619 15.03928083
 20.46300358]

In [ ]:
ypredict = model.predict(xtest)
print (f"the independent values are {xtest}")
print (f"the dependent values are {ypredict}")

the independent values are         additional_charges
657510                3.54
90029                 2.36
373608                1.28
332985                2.37
458875                3.26
...                    ...
540565                4.91
170586                2.91
620978                1.32
196694               18.35
313831                0.00

[115097 rows x 1 columns]
the dependent values are [20.48668796 17.69193126 15.13401834 ... 15.22875586 55.56325301
 12.10241785]

In [ ]:
#NO 2
df = pd.read_csv('/content/drive/My Drive/rideshare_2022.csv')
clean =df.dropna()
clean.head(5)

,Trip ID,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,...,Trip Total,Shared Trip Authorized,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,len_date
3,36c8a2a4cd85fb32ae32170550d2a4d30b8df8a1,01/01/2022 00:00,01/01/2022 00:15,243.0,1.0,1.703106e+10,1.703106e+10,6.0,6.0,5.0,...,7.36,0,1,41.936310,-87.651563,POINT (-87.6515625922 41.9363101308),41.943155,-87.640698,POINT (-87.640698076 41.9431550855),16
4,493f7bbcba1d96bf10bd579fe1c4b7ddb95fd3a6,01/01/2022 00:00,01/01/2022 00:15,364.0,1.3,1.703107e+10,1.703106e+10,7.0,6.0,5.0,...,7.36,0,1,41.921855,-87.646211,POINT (-87.6462109769 41.9218549112),41.936237,-87.656412,POINT (-87.6564115308 41.9362371791),16
5,5d07bc7d3534b93fd0c862b69b161857a6f43f52,01/01/2022 00:00,01/01/2022 00:15,467.0,2.2,1.703107e+10,1.703124e+10,7.0,24.0,7.5,...,9.91,0,1,41.928763,-87.665677,POINT (-87.665676837 41.9287630064),41.899737,-87.664954,POINT (-87.6649539167 41.8997373884),16
8,8e49900df0154a3f1fe40fdff266a11d01a7f121,01/01/2022 00:00,01/01/2022 00:15,315.0,1.2,1.703184e+10,1.703183e+10,32.0,28.0,7.5,...,10.37,0,1,41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),41.885281,-87.657233,POINT (-87.6572331997 41.8852813201),16
11,be1aadeb82f5fb96fb05dfc8ff36a7908e529a44,01/01/2022 00:00,01/01/2022 00:15,964.0,1.5,1.703183e+10,1.703132e+10,28.0,32.0,10.0,...,17.87,0,1,41.885281,-87.657233,POINT (-87.6572331997 41.8852813201),41.884987,-87.620993,POINT (-87.6209929134 41.8849871918),16

In [ ]:
FA = clean['Fare'].head(5)
TT = clean['Trip Total'].head(5)
print(FA)
print(TT)

3      5.0
4      5.0
5      7.5
8      7.5
11    10.0
Name: Fare, dtype: float64
3      7.36
4      7.36
5      9.91
8     10.37
11    17.87
Name: Trip Total, dtype: float64

In [ ]:
nFA = np.array(FA)
nTT = np.array(TT)

t_test, p_value = stats.ttest_ind(nFA, nTT,equal_var=True)
t_test2, p_value2 = stats.ttest_ind(nFA, nTT)
print(t_test, p_value)

-1.667530919029978 0.13396593585159652

In [ ]:
df = 8
alpha = 0.05
t_critical = stats.t.ppf(1-alpha/2,df)
print(t_critical)

2.306004135204166

In [ ]:
if(t_critical < abs(t_test)):
  print("Reject null hypothesis")
else:
  print("Accept null hypothesis")

Accept null hypothesis

In [ ]:
x = clean[['Fare']]
y = clean['Trip Total']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(296543, 1)
(74136, 1)
(296543,)
(74136,)

In [ ]:
x = clean[['Fare']]
y = clean['Trip Total']
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=42)
print(f"the dataset for training is {xtrain}")
print(f"the dataset for testing is {xtest}")
print(f"the target for training is {ytrain}")
print(f"the target for testing is {ytest}")

the dataset for training is         Fare
414504   7.5
175954  12.5
206228  17.5
141471  12.5
431736  12.5
...      ...
487564  12.5
682361   7.5
250192  20.0
277921  20.0
232284  12.5

[296543 rows x 1 columns]
the dataset for testing is         Fare
238792   7.5
382830  12.5
477050  17.5
256720  20.0
505816  35.0
...      ...
212407  22.5
524518  10.0
94730   12.5
541659  20.0
624267   7.5

[74136 rows x 1 columns]
the target for training is 414504    12.16
175954    18.47
206228    22.18
141471    15.62
431736    18.14
          ...
487564    15.76
682361    12.16
250192    21.24
277921    24.00
232284    12.50
Name: Trip Total, Length: 296543, dtype: float64
the target for testing is 238792    12.32
382830    15.92
477050    20.41
256720    26.01
505816    46.88
          ...
212407    29.56
524518    14.34
94730     15.50
541659    25.84
624267    17.30
Name: Trip Total, Length: 74136, dtype: float64

In [ ]:
bee = LinearRegression().fit(xtrain,ytrain)

In [ ]:
ypredict = bee.predict(xtrain)
print (f"the predicted values are {ypredict}")

the predicted values are [11.21903052 17.18383648 23.14864245 ... 26.13104543 26.13104543
 17.18383648]

In [ ]:
ypredict = bee.predict(xtest)
print (f"the independent values are {xtest}")
print (f"the dependent values are {ypredict}")

the independent values are         Fare
238792   7.5
382830  12.5
477050  17.5
256720  20.0
505816  35.0
...      ...
212407  22.5
524518  10.0
94730   12.5
541659  20.0
624267   7.5

[74136 rows x 1 columns]
the dependent values are [11.21903052 17.18383648 23.14864245 ... 17.18383648 26.13104543
 11.21903052]